### ISSUE TITLE
Many functions related to Pymc library is deprecated and are quite difficult to migrate to Pymc3...

### ISSUE THREAD

**Issue by Leiguo924** [aleximorin/TimeDeltaBayesianModel#2]
Dear Alex,

I personally appreciate your contribution of this work for inversing the ice thickness of surging glaciers.

I have been working on this code for a few days. However, i noticed that many pymc2 related functions in your code has been deprecated, as mentioned in another issue. I have tried to track the usage of these deprecated functions, however, it's almost impossible (such as `pm.gp.observe`)... Maybe you have used an outdated version of pymc?

I'm wondering if this work could be migrated to pymc3 to for better compatibility?  Its current form is too hard to replicate.

**Comment by aleximorin** [comment]
Hello,

Sorry for the delay in my response. I have provided an environment.yml file which should help you in having a proper conda environment to conduct your experiments. I have tried to install it as a fresh environment on my machine and the code works, let me know if it does for you.

**Comment by nonoonoo** [comment]
Hi, thank you very much for your reply, I created the environment using the yml file you provided, but I'm encountering an issue when running the `synthetic_example.py` and `realdata_example.py` code. The traceback I get is as follows:
```
Traceback (most recent call last):
  File "E:\Pycharm\PyCharm 2021.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Pycharm\PyCharm 2021.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Allcode/TimeDeltaBayesianModel-main/synthetic_example.py", line 97, in <module>
    model.setup_model(mesh)
  File "D:\Allcode\TimeDeltaBayesianModel-main\TimeDeltaBayesianModel.py", line 75, in setup_model
    glacier.set_gp_priors(mesh)
  File "D:\Allcode\TimeDeltaBayesianModel-main\GlacierModel.py", line 76, in set_gp_priors
    self.dem.set_gaussianprocess(mesh, positive_init=True)
  File "D:\Allcode\TimeDeltaBayesianModel-main\SimpleRaster.py", line 184, in set_gaussianprocess
    self.gp = pm.gp.GPSubmodel(self.tag, M, C, self.mesh, init_vals=init_vals)
  File "E:\mambaforge\envs\tdbm\lib\site-packages\pymc\gp\gp_submodel.py", line 249, in __init__
    def fr_check(S_eval=S_eval):
  File "E:\mambaforge\envs\tdbm\lib\site-packages\pymc\InstantiationDecorators.py", line 209, in instantiate_pot
    return Potential(parents=parents, **kwds)
  File "E:\mambaforge\envs\tdbm\lib\site-packages\pymc\PyMCObjects.py", line 281, in __init__
    if not isinstance(self.logp, float):
  File "E:\mambaforge\envs\tdbm\lib\site-packages\pymc\PyMCObjects.py", line 334, in get_logp
    raise ZeroProbability(self.errmsg)
pymc.Node.ZeroProbability: Potential Steady state_dem_fr_check forbids its parents' current values
```
Can you provide some guidance on how to resolve this issue?

**Comment by aleximorin** [comment]
I modified the provided examples and it should work.

The problem, to my comprehension, is that we are sampling the Gaussian processes on very small grids as compared to their lengthscales and observational variance. This causes the covariance matrices to be highly correlated and thus numerically singular. To fix the problem, we can simply reduce the lengthscale (which I did in the examples) or coarsen the grid. 

To fix it on my install and to understand what was going on, I dwelved into the pymc code (which I recommend you do if you want to have an understanding of what's going on) and slightly modified the [Covariance.py](https://github.com/pymc-devs/pymc2/blob/master/pymc/gp/Covariance.py) file to add a small value on the diagonal. 

[Here's a very good video](https://www.youtube.com/watch?v=92-98SYOdlY&t=831s) to get a better insight into Gaussian processes

**Comment by nonoonoo** [comment]
Thank you for the reply and for taking the time to solve the issue. I'm glad you were able to get the examples working with these fixes. Your advice is very helpful to me. Thanks again for the helpful feedback!
